# Generated by Django 4.2.6 on 2023-10-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EmployeeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="DepartmentId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="departments",
            name="DepartmentName",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="departments",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="departments",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="employees",
            name="Department",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employees",
            name="EmployeeId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employees",
            name="EmployeeName",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employees",
            name="PhotoFileName",
            field=models.CharField(max_length=100),
        ),
    ]
