# Generated by Django 4.2.6 on 2023-11-02 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("EmployeeApp", "0003_employees_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employees",
            name="image",
        ),
    ]
