# Generated by Django 4.2.6 on 2023-11-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EmployeeApp", "0004_remove_employees_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="DateOfJoining",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="employees",
            name="Department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="employees",
            name="PhotoFileName",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
